#include "CastleNoteSequence.h"


// AUTOGENERATED FILE
// DO NOTE EDIT
// UPDATE compilers/SequencesCompiler/Sequences AND RUN "make sequences-(debug|release)"
CastleNoteSequence::CastleNoteSequence() {
    m_musicFileName = "castle_bg.ogg";
    m_tempo = 4; //  a tempo of 4 = 60 bpms

    // offsets are in percentages of bar size
    /*
        whole note   = 1.0
        half note    = 0.5
        quarter note = 0.25
        eigth note   = 1/8
        16th note    = 1/16
    */
    // m_notes.push_back(NoteData(sf::Vector2f(length, row)));
	m_notes.push_back(NoteData(sf::Vector2f(0.25, 1)));
	m_notes.push_back(NoteData(sf::Vector2f(0.25, 2)));
	m_notes.push_back(NoteData(sf::Vector2f(0.25, 1)));
	m_notes.push_back(NoteData(sf::Vector2f(0.125, 2)));
	m_notes.push_back(NoteData(sf::Vector2f(0.125, 3)));
}

CastleNoteSequence::~CastleNoteSequence() {}

std::string CastleNoteSequence::GetMusicFileName() {
    return m_musicFileName;
}

Notes CastleNoteSequence::GetNotes() {
    return m_notes;
}