#include "Enemy1NoteSequence.h"


// AUTOGENERATED FILE
// DO NOTE EDIT
// UPDATE compilers/SequencesCompiler/Sequences AND RUN "make sequences-(debug|release)"
Enemy1NoteSequence::Enemy1NoteSequence() {
    m_musicFileName = "castle_enemy_1.ogg";
    m_tempo = 4; //  a tempo of 4 = 60 bpms

    // offsets are in percentages of bar size
    /*
        whole note   = 1.0
        half note    = 0.5
        quarter note = 0.25
        eigth note   = 1/8
        16th note    = 1/16
    */
    // m_notes.push_back(NoteData(sf::Vector2f(length, row)));
	m_notes.push_back(NoteData(sf::Vector2f(0.5, 4)));
	m_notes.push_back(NoteData(sf::Vector2f(0.5, 1)));
}

Enemy1NoteSequence::~Enemy1NoteSequence() {}

std::string Enemy1NoteSequence::GetMusicFileName() {
    return m_musicFileName;
}

Notes Enemy1NoteSequence::GetNotes() {
    return m_notes;
}